Models/Car.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarRental.Models
{
    [Table("Cars")]
    public class Car
    {
        [Key]
        public int Id { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public decimal DailyPrice { get; set; }
        public int Seats { get; set; }
        public string Color { get; set; }
        public int Mileage { get; set; }
        public string ImageURL { get; set; }
        public int Doors { get; set; }
        public int Cylinders { get; set; }
        public int HP { get; set; }
        public string Description { get; set; }
    }
}

Models/DataContext.cs
using Microsoft.EntityFrameworkCore;

namespace CarRental.Models
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options) : base(options)
        {

        }
        // Define here below what of your model classes should have a table on the DB
        public DbSet<Car> Cars { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CarRental.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using CarRental.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CarRental.Controllers
{
    public class CatalogController : Controller
    {
        private DataContext db { get; set; }
        public CatalogController(DataContext context)
        {
            this.db = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpGet]
        // Endpoint to get the list of cars to show on catalog page
        public IActionResult GetCatalog()
        {
            List<Car> cars = db.Cars.ToList();
            return Json(cars);
        }

        [HttpPost]
        public IActionResult SaveCar([FromBody] Car carToRegister)
        {
            db.Cars.Add(carToRegister); // Add car (on memory only)
            db.SaveChanges(); // Submit changes to DB
            return Json(carToRegister);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CarRental.Models;

namespace CarRental.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            System.Console.WriteLine("The user wants the index view");
            return View();
        }

        public IActionResult Hello()
        {
            System.Console.WriteLine("The user wants the hello view");
            return View();
        }

        public IActionResult Privacy()
        {
            System.Console.WriteLine("The user wants the privacy view");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TestController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Homework2()
        {
            // Practice lists
            /* List<string> names = new List<string>();

            names.Add("Angelo");
            names.Add("John");
            names.Add("Jane");
            names.Add("Mark");

            for (int i = 0; i < names.Count; i++)
            {
                System.Console.WriteLine(names[i]);
            } */

            int num = 10;
            List<int> dividends = new List<int>();

            // Your code here

            return Json(dividends);
        }

        private int CountAndPrintOdds(int[] numbers)
        {
            int count = 0;

            // Print the odd numbers inside the array
            for (int i = 0; i < numbers.Length; i++)
            {
                int num = numbers[i];

                // Decide if num is an odd number
                int res = num % 2;
                if (res != 0)
                {
                    System.Console.WriteLine(num);
                    count += 1;
                }
            }

            return count;
        }

        public IActionResult Homework()
        {
            int[] numbers = new int[200];
            for (int i = 0; i < 200; i++)
            {
                numbers[i] = i + 1;
            }
            int howMany = CountAndPrintOdds(numbers);
            System.Console.WriteLine(howMany);

            System.Console.WriteLine("*****************************");
            System.Console.WriteLine("Homework");
            System.Console.WriteLine("*****************************");
            return Content("123");
        }
    }
}

Views/Catalog/Index.cshtml
@section Styles
{
<link rel="stylesheet" href="~/css/catalog.css">
}

<div id="catContainer" class="container-fluid">
    <div class="catalog row">
        <!-- Display the list of cars -->
    </div>
</div>

@section Scripts
{
<script src="~/js/catalog.js"></script>
}

Views/Catalog/Register.cshtml
@section Styles
{
<link rel="stylesheet" href="~/css/register.css">
}

<form>
  <div class="form-group row">
    <label for="imageURL" class="col-3 col-form-label">Image URL</label> 
    <div class="col-9">
      <input id="imageURL" name="imageURL" type="text" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="make" class="col-3 col-form-label">Make</label> 
    <div class="col-9">
      <input id="make" name="make" type="text" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="model" class="col-3 col-form-label">Model</label> 
    <div class="col-9">
      <input id="model" name="model" type="text" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="year" class="col-3 col-form-label">Year</label> 
    <div class="col-9">
      <input id="year" name="year" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="color" class="col-3 col-form-label">Color</label> 
    <div class="col-9">
      <input id="color" name="color" type="text" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="cylinders" class="col-3 col-form-label">Cylinders</label> 
    <div class="col-3">
      <input id="cylinders" name="cylinders" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="horsePower" class="col-3 col-form-label">Horsepower</label> 
    <div class="col-3">
      <input id="horsePower" name="horsePower" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="doors" class="col-3 col-form-label"># of Doors</label> 
    <div class="col-3">
      <input id="doors" name="doors" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="seats" class="col-3 col-form-label"># of Seats</label> 
    <div class="col-3">
      <input id="seats" name="seats" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="mileage" class="col-3 col-form-label"># of Mileage</label> 
    <div class="col-3">
      <input id="mileage" name="mileage" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="dailyPrice" class="col-3 col-form-label">Daily Price</label> 
    <div class="col-3">
      <input id="dailyPrice" name="dailyPrice" type="number" class="form-control">
    </div>
  </div>
  <div class="form-group row">
    <label for="description" class="col-3 col-form-label">Description</label> 
    <div class="col-9">
      <textarea id="description" name="description" cols="40" rows="5" class="form-control"></textarea>
    </div>
  </div> 
  <div class="form-group row">
    <div class="offset-3 col-9">
      <button id="btnSave" type="button" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>

@section Scripts
{
<script src="~/js/register.js"></script>
}

Views/Home/Hello.cshtml
<h1>This is hello page</h1>
<h3>Angelo Totanes</h3>
<h4>FSDI 110 Asp.net Rules!</h4>

<button class="btn btn-primary">Click me</button>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

Views/Home/Index.cshtml
@{
ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Car Rental</h1>
    <p>The best solution for vehichles!</p>
    <img src="https://www.detailxpertsfranchise.com/wp-content/uploads/2018/03/car-rent-1-e1519151734372.jpg"
        alt="Image Logo">
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarRental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Register">Register Car</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CarRental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Test/About.cshtml
<h1>Angelo Totanes</h1>

<h3>This is the about page of test controller</h3>

Views/Test/Index.cshtml
<h1>This is the index page of test controller</h1>